<?php

namespace Lddt\MainBundle\Repository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorRepository extends \Doctrine\ORM\EntityRepository
{
/*    public function findAllColors(){
        $q=$this->getEntityManager()
            ->createQuery("SELECT d,c FROM LddtMainBundle:Color d JOIN d.category c ORDER BY d.updatedAt DESC ");

        return $q->getResult();
    }*/
}
